/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalculatorButton: typeof import('./src/components/button/CalculatorButton.vue')['default']
    CalculatorButtons: typeof import('./src/components/button/CalculatorButtons.vue')['default']
    Contents: typeof import('./src/components/Contents.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    FormulaInput: typeof import('./src/components/input/FormulaInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
